### ISSUE TITLE
Failing to run wa after updating

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#1066]
Hi,
I just did a git update of devlib+wa and installed them. (sudo -H pip install .)

When I try to run my tests I have the following error:

Traceback (most recent call last):
  File "/usr/local/bin/wa", line 16, in <module>
    from wa.framework.entrypoint import main
  File "/usr/local/lib/python2.7/dist-packages/wa/__init__.py", line 16, in <module>
    from wa.framework import pluginloader, signal
  File "/usr/local/lib/python2.7/dist-packages/wa/framework/signal.py", line 29, in <module>
    from wa.utils.types import prioritylist, enum
  File "/usr/local/lib/python2.7/dist-packages/wa/utils/types.py", line 42, in <module>
    from collections.abc import MutableMapping
ImportError: No module named abc

**Comment by setrofim** [comment]
We have dropped support for Python 2 in the latest release. Please use `pip3` to install instead.

**Comment by dlezcano** [comment]
thanks!
