### ISSUE TITLE
WA hits python error under 32-bit ubuntu OS with python2.7

### ISSUE THREAD

**Issue by cloverpop** [ARM-software/workload-automation#183]
2016-06-20 15:16:09,738 DEBUG    android: adb -s 10.164.4.23:5555 pull '/sdcard/wa-working/cpufreq.tar.gz' 'wa_output/idle_big_big_idle_state0_1_1/cpufreq.tar.gz'
2016-06-20 15:16:10,042 ERROR    instrumentation: Error in insturment cpufreq
2016-06-20 15:16:10,044 ERROR    instrumentation:   File "/usr/local/lib/python2.7/dist-packages/wlauto/core/instrumentation.py", line 240, in __call__
2016-06-20 15:16:10,044 ERROR    instrumentation:     self.callback(context)
2016-06-20 15:16:10,044 ERROR    instrumentation:   File "/usr/local/lib/python2.7/dist-packages/wlauto/instrumentation/misc/__init__.py", line 166, in update_result
2016-06-20 15:16:10,044 ERROR    instrumentation:     tf.extractall(context.output_directory)
2016-06-20 15:16:10,044 ERROR    instrumentation:   File "/usr/lib/python2.7/tarfile.py", line 2079, in extractall
2016-06-20 15:16:10,044 ERROR    instrumentation:     self.extract(tarinfo, path)
2016-06-20 15:16:10,044 ERROR    instrumentation:   File "/usr/lib/python2.7/tarfile.py", line 2116, in extract
2016-06-20 15:16:10,044 ERROR    instrumentation:     self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
2016-06-20 15:16:10,044 ERROR    instrumentation:   File "/usr/lib/python2.7/tarfile.py", line 2209, in _extract_member
2016-06-20 15:16:10,044 ERROR    instrumentation:     self.utime(tarinfo, targetpath)
2016-06-20 15:16:10,044 ERROR    instrumentation:   File "/usr/lib/python2.7/tarfile.py", line 2330, in utime
2016-06-20 15:16:10,044 ERROR    instrumentation:     os.utime(targetpath, (tarinfo.mtime, tarinfo.mtime))
2016-06-20 15:16:10,044 ERROR    instrumentation: 
2016-06-20 15:16:10,044 ERROR    instrumentation: OverflowError(Python int too large to convert to C long)
2016-06-20 15:16:10,044 DEBUG    instrumentation: Disabling instrument cpufreq

Even if we write standalone demo python script under the same environment ( copy cpufreq.tar.gz to local folder),  there will be the same error. 

Traceback (most recent call last):
  File "test.py", line 25, in <module>
    main()
  File "test.py", line 20, in main
    tf.extractall("./")
  File "/usr/lib/python2.7/tarfile.py", line 2079, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib/python2.7/tarfile.py", line 2116, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib/python2.7/tarfile.py", line 2209, in _extract_member
    self.utime(tarinfo, targetpath)
  File "/usr/lib/python2.7/tarfile.py", line 2330, in utime
    os.utime(targetpath, (tarinfo.mtime, tarinfo.mtime))
OverflowError: Python int too large to convert to C long

**Comment by ep1cman** [comment]
Hi,
This seems to be an issue with python rather than WA. It looks like the timestamp of the files is set beyond 2038-1-19 (which would put it over the maximum value for a 32-bit integer). Can you check the date on the target device?

**Comment by cloverpop** [comment]
Yes, this issue can be resolved under 64-bit Ubuntu OS.

**Comment by setrofim** [comment]
Please could you confirm what date is being set on the target device?

**Comment by cloverpop** [comment]
It's something like:

root@juno:/s # date
Fri Apr  9 22:51:07 GMT 2066

**Comment by ep1cman** [comment]
Ah then there is your problem. A 32-bit integer cannot represent a date past 2038-01-19. This is a fundamental limitation of 32-bit operating systems not an issue with WA. I would recommend either setting the correct date on the target device and/or switching to a 64-bit operating system.
