### ISSUE TITLE
WA2 support on Android 7.0

### ISSUE THREAD

**Issue by nareshkamboju** [ARM-software/workload-automation#274]
Hi Team,

Workload automation failed to run UiAutomator on latest Android version 7.0
I think we have to generate new .jar files to cope with Android 7.0

9.1561   2016-09-16 00:31:46,513 ERROR Runner:  com.android.uiautomator.core.UiObjectNotFoundException: UiSelector[TEXT=Performance Tests, CLASS=android.widget.TextView]  
9.1562   2016-09-16 00:31:46,513 ERROR Runner:   at com.android.uiautomator.core.UiObject.clickAndWaitForNewWindow(UiObject.java:439)  
9.1563   2016-09-16 00:31:46,513 ERROR Runner:   at com.android.uiautomator.core.UiObject.clickAndWaitForNewWindow(UiObject.java:417)  
9.1564   2016-09-16 00:31:46,513 ERROR Runner:   at com.arm.wlauto.uiauto.glb.UiAutomation.goToPreformanceTestsMenu(UiAutomation.java:75)  
9.1565   2016-09-16 00:31:46,513 ERROR Runner:   at com.arm.wlauto.uiauto.glb.UiAutomation.runUiAutomation(UiAutomation.java:51)  
9.1566   2016-09-16 00:31:46,513 ERROR Runner:   at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)  
9.1567   2016-09-16 00:31:46,513 ERROR Runner:   at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)  
9.1568   2016-09-16 00:31:46,513 ERROR Runner:   at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)  
9.1569   2016-09-16 00:31:46,513 ERROR Runner:   at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)  
9.1570   2016-09-16 00:31:46,513 ERROR Runner:   at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)  
9.1571   2016-09-16 00:31:46,513 ERROR Runner:   at com.android.

**Comment by siddhanathan** [comment]
As indicated by the warning:

```
ERROR    	Warning: This version of UI Automator is deprecated. New tests should be written using
ERROR    	UI Automator 2.0 which is available as part of the Android Testing Support Library.
ERROR    	See https://developer.android.com/training/testing/ui-testing/uiautomator-testing.html
ERROR    	for more details.
```

**Comment by lisatn** [comment]
Following to see if there's a fix for the UI Automation 2.0 issue. I tried running the Skype and googlephotos workload on Android N, and they give me similar errors:

2017-02-03 18:09:17,283 ERROR    Runner: Error while running workload:
2017-02-03 18:09:17,283 ERROR    Runner:        Warning: This version of UI Automator is deprecated. New tests should be written using
2017-02-03 18:09:17,283 ERROR    Runner:        UI Automator 2.0 which is available as part of the Android Testing Support Library.
2017-02-03 18:09:17,283 ERROR    Runner:        See https://developer.android.com/training/testing/ui-testing/uiautomator-testing.html
2017-02-03 18:09:17,283 ERROR    Runner:        for more details.
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: numtests=1
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: stream=
2017-02-03 18:09:17,283 ERROR    Runner:        com.arm.wlauto.uiauto.googlephotos.UiAutomation:
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: test=runUiAutomation
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.googlephotos.UiAutomation
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: current=1
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS_CODE: 1
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: numtests=1
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: stream=
2017-02-03 18:09:17,283 ERROR    Runner:        Error in runUiAutomation:
2017-02-03 18:09:17,283 ERROR    Runner:        com.android.uiautomator.core.UiObjectNotFoundException: Could not find "com.google.android.apps.photos:id/name" "android.widget.TextView"
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByResourceId(BaseUiAutomation.java:517)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByResourceId(BaseUiAutomation.java:510)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:488)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:479)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.googlephotos.UiAutomation.dismissWelcomeView(UiAutomation.java:102)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.googlephotos.UiAutomation.runUiAutomation(UiAutomation.java:54)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
2017-02-03 18:09:17,283 ERROR    Runner:
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: test=runUiAutomation
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.googlephotos.UiAutomation
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: Could not find "com.google.android.apps.photos:id/name" "android.widget.TextView"
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByResourceId(BaseUiAutomation.java:517)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByResourceId(BaseUiAutomation.java:510)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:488)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:479)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.googlephotos.UiAutomation.dismissWelcomeView(UiAutomation.java:102)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.arm.wlauto.uiauto.googlephotos.UiAutomation.runUiAutomation(UiAutomation.java:54)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2017-02-03 18:09:17,283 ERROR    Runner:                at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
2017-02-03 18:09:17,283 ERROR    Runner:
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: current=1
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS_CODE: -1
2017-02-03 18:09:17,283 ERROR    Runner:        INSTRUMENTATION_STATUS: stream=
2017-02-03 18:09:17,283 ERROR    Runner:        Test results for WatcherResultPrinter=.E
2017-02-03 18:09:17,283 ERROR    Runner:        Time: 21.919

**Comment by setrofim** [comment]
We are aware of these issues, however migrating to UIAutomator2 is a substantial piece of work, which we currently have planned for Q2.

**Comment by marcbonnici** [comment]
Migration to UiAutomator2 completed with pull request 3653e1b507d707a934147fdc63de545b49591f6c
