### ISSUE TITLE
Failed to run WA3

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#602]
Hi WA team,

I was using WA2 successfully. Now I'm switching to the WA3 dev branch 'next'.
I followed the instructions in the README.rst file and installed WA3 but when I try to run it I get:

Traceback (most recent call last):
  File "/usr/local/bin/wa", line 16, in <module>
    from wa.framework.entrypoint import main
  File "/usr/local/lib/python2.7/dist-packages/wa/__init__.py", line 13, in <module>
    from wa.framework.output import RunOutput, discover_wa_outputs
  File "/usr/local/lib/python2.7/dist-packages/wa/framework/output.py", line 8, in <module>
    from wa.framework.configuration.execution import CombinedConfig
  File "/usr/local/lib/python2.7/dist-packages/wa/framework/configuration/execution.py", line 7, in <module>
    from wa.framework.configuration.plugin_cache import PluginCache
  File "/usr/local/lib/python2.7/dist-packages/wa/framework/configuration/plugin_cache.py", line 24, in <module>
    from wa.framework.target.descriptor import list_target_descriptions
  File "/usr/local/lib/python2.7/dist-packages/wa/framework/target/descriptor.py", line 4, in <module>
    from devlib import (LinuxTarget, AndroidTarget, LocalLinuxTarget,
ImportError: cannot import name ChromeOsTarget

Is it a known issue ?

**Comment by setrofim** [comment]
Please make sure that you've installed the latest delvib master: https://github.com/ARM-software/devlib

**Comment by dlezcano** [comment]
Thanks for your quick answer.

I installed the latest version of devlib (4.0.0) and that fixed the issue.
