### ISSUE TITLE
pcmark fails on android Q

### ISSUE THREAD

**Issue by qais-yousef** [ARM-software/workload-automation#907]
Using Linaro's latest Android snapshot images of aosp/master (Android Q), pcmark fails because there's a new pop on application launch that complains about "This app was built for an older version of Android...." which breaks uiAutomation with this splatter

```
ERROR            INSTRUMENTATION_STATUS: class=com.arm.wa.uiauto.pcmark.UiAutomation                                                                                                                        
ERROR            INSTRUMENTATION_STATUS: current=1                                                                                                                                                          
ERROR            INSTRUMENTATION_STATUS: id=AndroidJUnitRunner                                                                                                                                              
ERROR            INSTRUMENTATION_STATUS: numtests=1                                                                                                                                                         
ERROR            INSTRUMENTATION_STATUS: stream=                                                                                                                                                            
ERROR            com.arm.wa.uiauto.pcmark.UiAutomation:                                                                                                                                                     
ERROR            INSTRUMENTATION_STATUS: test=setup                                                                                                                                                         
ERROR            INSTRUMENTATION_STATUS_CODE: 1                                                                                                                                                             
ERROR            INSTRUMENTATION_STATUS: class=com.arm.wa.uiauto.pcmark.UiAutomation                                                                                                                        
ERROR            INSTRUMENTATION_STATUS: current=1                                                                                                                                                          
ERROR            INSTRUMENTATION_STATUS: id=AndroidJUnitRunner                                                                                                                                              
ERROR            INSTRUMENTATION_STATUS: numtests=1                                                                                                                                                         
ERROR            INSTRUMENTATION_STATUS: stack=android.support.test.uiautomator.UiObjectNotFoundException: Application has not loaded within the given time                                                 
ERROR                   at com.arm.wa.uiauto.pcmark.UiAutomation.loadBenchmarks(UiAutomation.java:78)                                                                                                       
ERROR                   at com.arm.wa.uiauto.pcmark.UiAutomation.setup(UiAutomation.java:49)                                                                                                                
ERROR                   at java.lang.reflect.Method.invoke(Native Method)                                                                                                                                   
ERROR                   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)                                                                                             
ERROR                   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)                                                                                              
ERROR                   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)                                                                                               
ERROR                   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)                                                                                                
ERROR                   at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)                   
.
.
.
.
.
```
I could fix it using the patch below

```
diff --git a/wa/workloads/pcmark/uiauto/app/src/main/java/com/arm/wa/uiauto/pcmark/UiAutomation.java b/wa/workloads/pcmark/uiauto/app/src/main/java/com/arm/wa/uiauto/pcmark/UiAutomation.java
index 7bd6e96e..fe4d147d 100755
--- a/wa/workloads/pcmark/uiauto/app/src/main/java/com/arm/wa/uiauto/pcmark/UiAutomation.java
+++ b/wa/workloads/pcmark/uiauto/app/src/main/java/com/arm/wa/uiauto/pcmark/UiAutomation.java
@@ -37,6 +37,7 @@ public class UiAutomation extends BaseUiAutomation {
     private int networkTimeoutSecs = 30;
     private long networkTimeout =  TimeUnit.SECONDS.toMillis(networkTimeoutSecs);
     public static String TAG = "UXPERF";
+    public static final long WAIT_TIMEOUT_5SEC = TimeUnit.SECONDS.toMillis(5);
 
     @Before
     public void initialize(){
@@ -45,6 +46,7 @@ public class UiAutomation extends BaseUiAutomation {
 
     @Test
     public void setup() throws Exception{
+        dismissPopup();
         setScreenOrientation(ScreenOrientation.NATURAL);
         loadBenchmarks();
         installBenchmark();
@@ -60,6 +62,18 @@ public class UiAutomation extends BaseUiAutomation {
         unsetScreenOrientation();
     }
 
+    // If we run the app in newer Android we'll get a popup complaining about
+    // that, silently accept it and carry on.
+    // This function should act as a NOP if no popup appears.
+    public void dismissPopup() throws Exception {
+        UiObject acceptButton =
+           mDevice.findObject(new UiSelector().resourceId("android:id/button1")
+                                         .className("android.widget.Button"));
+        if (acceptButton.waitForExists(WAIT_TIMEOUT_5SEC)) {
+            acceptButton.click();
+        }
+    }
+
     //Swipe to benchmarks and back to initialise the app correctly
     private void loadBenchmarks() throws Exception {
         UiObject title = 

```

I'd be happy to push this as a PR, I stole the dismissEula() function from geekbench workload uiautomation and slightly modified it to silently wait for a pop up and dismiss it or quitely carry on so should work for all versions I believe.

But maybe you know something better :)

**Comment by marcbonnici** [comment]
I would say that is probably the best solution we have at the moment so if you would be able to create a PR that would be great thanks.

**Comment by qais-yousef** [comment]
Cool shall do. I must update the apk file as part of the PR, correct?

**Comment by marcbonnici** [comment]
This should be fixed with https://github.com/ARM-software/workload-automation/pull/908
